run:
  timeout: 5m
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gosec
    - misspell
    - revive
    - unused
    - whitespace
linters-settings:
  goimports:
    local-prefixes: github.com/oculus-core/gogo
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
